version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache-entregafinal
    image: php:8.0-apache
    volumes:
      - ./src/entregaFinal/public:/var/www/html/
    ports:
      - 80:80
  mysql:
    image: mysql
    platform: linux/amd64
    restart: always
    ports: 
      - 3306:3306
    environment: 
        MYSQL_ROOT_HOST: localhost
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: toor
        MYSQL_USER: user
        MYSQL_PASSWORD: user

    volumes: 
    - ./init:/docker-entrypoint-initdb.d
    - app_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8686:8080
  
  web:
    build: './php/'
    ports:
      - 8787:8080
    volumes:
      - ./www:/var/www/html
    links: 
      - mysql
volumes: 
  app_db:

networks: 
  nt_mysql:
    driver: bridge
